In [4]:
import numpy as np
import time
# import taichi as ti
# ti.init(arch=ti.cpu) # 选择CPU作为后端

## 向量化与 For 循环

In [5]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [8]:
# Vectorization
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print("c = a*b =", c)
print("向量计算时间: " + str(1000*(toc-tic)) + " ms")

# For loop
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]

toc = time.time()
print("c = a*b =", c)
print("For loop 计算时间: " + str(1000*(toc-tic)) + " ms")

c = a*b = 250045.07865353418
向量计算时间: 1.0628700256347656 ms
c = a*b = 250045.07865353642
For loop 计算时间: 304.1996955871582 ms


## Broadcasting 广播机制

In [12]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

# 按列求和, 垂直方向求和
cal = A.sum(axis=0)

# 计算百分比
percentage = 100*A/cal.reshape(1,4)

In [14]:
print("矩阵A: \n", A)
print("每一列总和: \n", cal)
print("每项占比: \n", percentage)

矩阵A: 
 [[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
每一列总和: 
 [ 59.  239.  155.4  76.9]
每项占比: 
 [[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
